#!/bin/sh

FILES="./tests/entry.c ./src/generator.c ./src/parser.c \
./include/libnavigate/iecgenerator.h \
./include/libnavigate/iecparser.h \
./include/libnavigate/iecsentence.h"

for i in $FILES
do
	sed  -r 's/[:space:]_DTM/ naviSentence_DTM/g' $i
	sed  -r 's/[:space:]_GLL/ naviSentence_GLL/g' $i
	sed  -r 's/[:space:]_GNS/\ naviSentence_GNS/g' $i
	sed  -r 's/[:space:]_RMC/\ naviSentence_RMC/g' $i
	sed  -r 's/[:space:]_VTG/\ naviSentence_VTG/g' $i
	sed  -r 's/[:space:]_ZDA/\ naviSentence_ZDA/g' $i
done

exit 0

